name: protein_fitness_prediction
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - abseil-cpp=20200225.2=he1b5a44_2
  - appdirs=1.4.3=py_1
  - argcomplete=1.12.1=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py37h8f50634_1
  - arrow-cpp=1.0.1=py37h880e8b3_13_cpu
  - arviz=0.10.0=py_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - atk=2.36.0=2
  - atk-1.0=2.36.0=h516909a_2
  - atpublic=1.0=py_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - aws-c-common=0.4.59=he1b5a44_0
  - aws-c-event-stream=0.1.6=h84e28f3_5
  - aws-checksums=0.1.9=he252421_2
  - aws-sdk-cpp=1.8.59=h9b98462_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bcrypt=3.2.0=py37h8f50634_0
  - billiard=3.6.3.0=py37h8f50634_2
  - binutils_impl_linux-64=2.35=h18a2f87_9
  - binutils_linux-64=2.35=hc3fd857_29
  - biopython=1.78=py37h8f50634_0
  - bleach=3.2.1=pyh9f0ad1d_0
  - blinker=1.4=py_1
  - boto3=1.15.16=pyh9f0ad1d_0
  - brotli=1.0.9=he1b5a44_2
  - brotlipy=0.7.0=py37h8f50634_1000
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.1.1=py_0
  - cairo=1.16.0=h3fc0475_1005
  - certifi=2020.12.5=py37h89c1867_0
  - cffi=1.14.3=py37h2b28604_0
  - cftime=1.2.1=py37h161383b_1
  - chardet=3.0.4=py37he5f6b98_1008
  - colorama=0.4.3=py_0
  - commonmark=0.9.1=py_0
  - configobj=5.0.6=py_0
  - crcmod=1.7=py37hc8dfbb8_1003
  - cryptography=3.1.1=py37hb09aad4_0
  - cudatoolkit=10.1.243=h036e899_6
  - cudnn=7.6.5=cuda10.1_0
  - curl=7.71.1=he644dc0_8
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distro=1.5.0=pyh9f0ad1d_0
  - dvc=1.8.1=py37hc8dfbb8_0
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=he1b5a44_2
  - fastprogress=1.0.0=py_0
  - filelock=3.0.12=pyh9f0ad1d_0
  - flatten-dict=0.3.0=pyh9f0ad1d_0
  - flufl.lock=3.2=py_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.030=hab24e00_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h1056068_1002
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.3=he06d7ca_0
  - fribidi=1.0.10=h516909a_0
  - funcy=1.15=pyh9f0ad1d_0
  - future=0.18.2=py37hc8dfbb8_1
  - gcc_impl_linux-64=7.5.0=hd9e1a51_17
  - gcc_linux-64=7.5.0=he2a3fca_29
  - gdk-pixbuf=2.38.2=h3f25603_4
  - gettext=0.19.8.1=hc5be6a0_1002
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h516909a_2
  - gitdb=4.0.5=py_0
  - gitdb2=4.0.2=py_0
  - gitpython=3.1.9=py_0
  - glib=2.66.1=h680cd38_0
  - glog=0.4.0=h49b9bf7_3
  - gmp=6.2.0=he1b5a44_3
  - gobject-introspection=1.66.1=py37h619baee_1
  - google-api-core=1.22.4=pyh9f0ad1d_0
  - google-api-python-client=1.12.3=pyh9f0ad1d_0
  - google-auth-httplib2=0.0.4=pyh9f0ad1d_0
  - google-cloud-core=1.4.3=pyh9f0ad1d_0
  - google-cloud-storage=1.19.0=py_0
  - google-crc32c=1.0.0=py37h193935f_0
  - google-resumable-media=1.1.0=pyh9f0ad1d_0
  - googleapis-common-protos=1.52.0=py37hc8dfbb8_0
  - grandalf=0.6=py_0
  - graphite2=1.3.13=he1b5a44_1001
  - graphviz=2.42.3=h6939c30_2
  - grpc-cpp=1.32.0=h7997a97_1
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - gtk2=2.24.32=h194ddfc_3
  - gts=0.7.6=h08bb679_0
  - gxx_impl_linux-64=7.5.0=h7ea4de1_17
  - gxx_linux-64=7.5.0=h547f3ba_29
  - h5py=2.10.0=nompi_py37hf7afa78_105
  - harfbuzz=2.7.2=hee91db6_0
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.6=nompi_h54c07f9_1110
  - hhsuite=3.3.0=py37pl526hfa133b6_0
  - hmmer=3.3.1=he1b5a44_0
  - httplib2=0.18.1=pyh9f0ad1d_0
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - invoke=1.4.1=py_0
  - ipykernel=5.3.4=py37h43977f1_0
  - ipython=7.18.1=py37hc6149b9_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - isodate=0.6.0=py_1
  - jedi=0.17.2=py37hc8dfbb8_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=0.17.0=py_0
  - jpeg=9d=h516909a_0
  - jsonpath-ng=1.5.2=pyh9f0ad1d_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - kernel-headers_linux-64=2.6.32=h77966d4_13
  - kiwisolver=1.2.0=py37h99015e2_1
  - knack=0.6.3=py_0
  - krb5=1.17.1=hfafb76e_3
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.35=h769bd43_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=10.0.1=default_hde54327_1
  - libcrc32c=1.1.1=he1b5a44_2
  - libcurl=7.71.1=hcdd3856_8
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_2
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-devel_linux-64=7.5.0=h42c25f5_17
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - libgomp=9.3.0=h5dbcf3e_17
  - libgpuarray=0.7.6=h14c3975_1003
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=17_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnetcdf=4.7.4=nompi_hefab0ff_106
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.10=pthreads_hb3c22a3_5
  - libpng=1.6.37=hed695b0_2
  - libpq=12.3=h5513abc_0
  - libprotobuf=3.13.0.1=h8b12597_0
  - libsodium=1.0.18=h516909a_1
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-devel_linux-64=7.5.0=h4084dd6_17
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libthrift=0.13.0=h5aa387f_6
  - libtiff=4.1.0=hc7e4089_6
  - libtool=2.4.6=h516909a_1005
  - libutf8proc=2.5.0=h516909a_2
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.1.0=h56121f0_4
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=h68273f3_2
  - llvm-openmp=8.0.1=hc9558a2_0
  - lz4-c=1.9.2=he1b5a44_3
  - mako=1.1.3=pyh9f0ad1d_0
  - markupsafe=1.1.1=py37hb5d75c8_2
  - matplotlib-base=3.3.2=py37hd478181_0
  - mistune=0.8.4=py37h8f50634_1002
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37h8f50634_2
  - msrest=0.6.19=pyh9f0ad1d_0
  - mysql-common=8.0.21=2
  - mysql-libs=8.0.21=hf3661c5_2
  - nanotime=0.5.2=py_0
  - nbclient=0.5.0=py_0
  - nbconvert=6.0.7=py37hc8dfbb8_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he1b5a44_2
  - nest-asyncio=1.4.1=py_0
  - netcdf4=1.5.4=nompi_py37hcbfd489_103
  - networkx=2.4=py_1
  - ninja=1.10.2=h4bd325d_0
  - notebook=6.1.4=py37hc8dfbb8_0
  - nspr=4.29=he1b5a44_0
  - nss=3.57=he751ad9_0
  - numpy=1.18.5=py37h8960a57_0
  - oauth2client=4.1.3=py_0
  - olefile=0.46=py_0
  - openmp=8.0.1=0
  - openssl=1.1.1i=h7f98852_0
  - orc=1.6.5=hd3605a7_0
  - oss2=2.13.0=py37hc8dfbb8_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.3=py37h9fdb41a_2
  - pandoc=2.11=hd18ef5c_0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=h7062337_4
  - paramiko=2.7.2=pyh9f0ad1d_0
  - parquet-cpp=1.5.1=2
  - parso=0.7.0=pyh9f0ad1d_0
  - pathlib2=2.3.5=py37hc8dfbb8_1
  - pathspec=0.8.0=pyh9f0ad1d_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=7.2.0=py37h718be6c_2
  - pip=20.2.3=py_0
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pyaml=20.4.0=pyh9f0ad1d_0
  - pyarrow=1.0.1=py37hcae2be3_13_cpu
  - pyasn1=0.4.8=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pycryptodome=3.9.8=py37hb05bdb2_1
  - pydot=1.4.1=py37hc8dfbb8_1002
  - pydrive2=1.6.2=pyh9f0ad1d_0
  - pygments=2.7.1=py_0
  - pygpu=0.7.6=py37h161383b_1002
  - pygtrie=2.3.2=pyh8c360ce_0
  - pyjwt=1.7.1=py_0
  - pymc3=3.9.3=py_1
  - pynacl=1.4.0=py37h8f50634_1
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h8685d9f_3
  - pyrsistent=0.17.3=py37h8f50634_1
  - pysocks=1.7.1=py37he5f6b98_2
  - python=3.7.6=cpython_h8356626_6
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py37hb5d75c8_1
  - pyzmq=19.0.2=py37hac76be4_2
  - qt=5.12.9=h1f2b2cb_0
  - qtconsole=4.7.7=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - re2=2020.10.01=he1b5a44_0
  - readline=8.0=he28a2e2_2
  - requests=2.24.0=pyh9f0ad1d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rich=8.0.0=py37hc8dfbb8_0
  - ruamel.yaml=0.16.12=py37h8f50634_1
  - ruamel.yaml.clib=0.2.2=py37h8f50634_1
  - s3transfer=0.3.3=py37hc8dfbb8_1
  - scikit-learn=0.23.1=py37h8a51577_0
  - scikit-optimize=0.8.1=pyh9f0ad1d_0
  - seaborn=0.10.1=1
  - seaborn-base=0.10.1=py_1
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py37he5f6b98_2
  - setuptools-scm=4.1.2=pyh9f0ad1d_0
  - setuptools_scm=4.1.2=0
  - shortuuid=1.0.1=py37hc8dfbb8_3
  - shtab=1.3.2=pyh9f0ad1d_0
  - simplejson=3.17.2=py37h8f50634_1
  - six=1.15.0=pyh9f0ad1d_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - snappy=1.1.8=he1b5a44_3
  - sqlite=3.33.0=h4cf870e_1
  - statsmodels=0.12.0=py37h8f50634_0
  - sysroot_linux-64=2.12=h77966d4_13
  - tabulate=0.8.7=pyh9f0ad1d_0
  - terminado=0.9.1=py37hc8dfbb8_0
  - testpath=0.4.4=py_0
  - theano=1.0.5=py37h745909e_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hed695b0_1
  - toml=0.10.1=pyh9f0ad1d_0
  - torchaudio=0.4.0=py37
  - torchvision=0.5.0=py37_cu101
  - tornado=6.0.4=py37h8f50634_2
  - tqdm=4.50.2=pyh9f0ad1d_0
  - traitlets=5.0.4=py_1
  - typing=3.7.4.3=py37hc8dfbb8_1
  - typing_extensions=3.7.4.2=py_0
  - uritemplate=3.0.1=py_0
  - voluptuous=0.11.7=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - widgetsnbextension=3.5.1=py37hc8dfbb8_1
  - xarray=0.16.1=py_0
  - xlrd=1.2.0=pyh9f0ad1d_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zc.lockfile=2.0=py_0
  - zeromq=4.3.3=he1b5a44_2
  - zipp=3.3.0=py_0
  - zlib=1.2.11=h516909a_1009
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - absl-py==0.9.0
    - aiohttp==3.6.3
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - astunparse==1.6.3
    - awscli==1.18.145
    - beautifulsoup4==4.9.3
    - blessings==1.7
    - bokeh==2.2.2
    - botocore==1.18.4
    - click==7.1.2
    - cloudpickle==1.3.0
    - colorful==0.5.4
    - dpath==2.0.1
    - editdistance==0.5.3
    - fair-esm==0.3.1
    - evcouplings==0.1.1
    - gast==0.3.3
    - google==3.0.0
    - google-auth==1.18.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - gpustat==0.6.0
    - grpcio==1.30.0
    - hiredis==1.1.0
    - keras-preprocessing==1.1.2
    - llvmlite==0.34.0
    - markdown==3.2.2
    - mmtf-python==1.1.2
    - msgpack==1.0.0
    - multidict==4.7.6
    - numba==0.51.2
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - opencensus==0.7.10
    - opencensus-context==0.1.1
    - opt-einsum==3.2.1
    - ply==3.11
    - protobuf==3.12.2
    - psutil==5.7.2
    - py-spy==0.3.3
    - pyasn1-modules==0.2.8
    - pynverse==0.1.4.4
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - redis==3.4.1
    - rsa==4.5
    - scipy==1.4.1
    - scons==4.0.1
    - sklearn==0.0
    - soupsieve==2.0.1
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.2.0
    - tensorflow-addons==0.10.0
    - tensorflow-estimator==2.2.0
    - tensorflow-probability==0.10.1
    - termcolor==1.1.0
    - typeguard==2.9.1
    - typing-extensions==3.7.4.3
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - yarl==1.5.1
